TGUI 4.3: Fix all remaining issues

diff --git a/tgui/bin/tgui b/tgui/bin/tgui
--- a/tgui/bin/tgui
+++ b/tgui/bin/tgui
@@ -98,6 +98,21 @@ task-clean() {
   rm -f **/package-lock.json
 }
 
+## Validates current build against the build stored in git
+## VOREStation Addition Start
+task-validate-build() {
+  cd "${base_dir}"
+  local diff
+  diff="$(git diff packages/tgui/public/tgui.bundle.*)"
+  if [[ -n ${diff} ]]; then
+    echo "Error: our build differs from the build committed into git."
+    echo "Please rebuild tgui."
+    exit 1
+  fi
+  echo "tgui: build is ok"
+}
+## VOREStation Addition End
+
 ## Installs merge drivers and git hooks
 task-install-git-hooks() {
   cd "${base_dir}"
@@ -151,6 +166,19 @@ if [[ ${1} == "--dev" ]]; then
   task-dev-server "${@}"
   exit 0
 fi
+
+## VOREStation Addition Start
+## Continuous integration scenario
+if [[ ${1} == "--ci" ]]; then
+  task-clean
+  task-install
+  task-lint
+  task-test
+  task-webpack --mode=production
+  task-validate-build
+  exit 0
+fi
+## VOREStation Addition End
 
 if [[ ${1} == '--lint' ]]; then
   shift 1
